org: drosenthal
app: turnstile
service: music-upload
frameworkVersion: '3'

custom:
  bucket: turnstile-music

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  upload:
    handler: functions/upload.handler
    events:
      - http:
          path: /file/upload
          method: POST
    environment:
      BUCKET: turnstile-music${opt:stage, 'dev'}