org: drosenthal
service: file-service
app: turnstile
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment: ${file(./env.${opt:stage, 'dev'}.js):getEnvVars}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
      Resource: 
        - arn:aws:s3:::turnstile-music-dev
        - arn:aws:s3:::turnstile-music-dev/*
        - arn:aws:s3:::turnstile-music
        - arn:aws:s3:::turnstile-music/*

custom:
  origins: 'https://turnstilemusic.vercel.app/,http://localhost:3000'

functions:
  uploadFile:
    handler: handlers/uploadFile.handler
    events:
      - http:
          path: upload-file
          method: POST
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
      - http:
          path: upload-file
          method: options
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
  fetchFiles:
    handler: handlers/fetchFiles.handler
    events:
      - http:
          path: fetch-files
          method: GET
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
      - http:
          path: fetch-files
          method: options
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true

plugins:
  - serverless-offline

package:
  exclude:
    - .env