org: drosenthal
app: turnstile
service: auth-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:stage, 'dev'}
  region: us-east-1

functions:
  signUp:
    handler: handler.signUp
    events:
      - http:
          path: sign-up
          method: POST
          cors: true

resources:
  Resources:
    TurnstilePoolDev:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: TurnstilePoolDev
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            
    TurnstileClientDev:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: TurnstilePoolClientDev
        UserPoolId: !Ref TurnstilePoolDev
        GenerateSecret: false


    TurnstilePoolProd:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: TurnstilePoolProd
        Schema:
          - Name: email
            Required: True
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            
    TurnstileClientProd:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: TurnstilePoolClientProd
        UserPoolId: !Ref TurnstilePoolProd
        GenerateSecret: false


custom:
  serverless-offline:
    httpPort: 3000

package:
  exclude:
    - .env
    - node_modules/**

plugins:
  - serverless-offline

useDotenv: true