org: drosenthal
service: auth-service
app: turnstile
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${env:stage, 'dev'}
  region: us-east-1
  environment: ${file(./cognitoEnv.${opt:stage, 'dev'}.js):getEnvVars}

custom:
  origins: 'https://turnstile-lemon.vercel.app/,http://localhost:3000,https://turnstile-7hq8sfy5d-danielrosenthal0.vercel.app'

functions:
  signUp:
    handler: handlers/signUp.handler
    events:
      - http:
          path: sign-up
          method: POST
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
      - http:
          path: sign-up
          method: options
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
  confirmSignUp:
    handler: handlers/confirmSignUp.handler
    events:
      - http:
          path: confirm-sign-up
          method: POST
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
      - http:
          path: confirm-sign-up
          method: options
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
  resendConfirmationCode:
    handler: handlers/resendConfirmationCode.handler
    events:
      - http:
          path: resend-confirmation-code
          method: POST
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
      - http:
          path: resend-confirmation-code
          method: options
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
  signIn:
    handler: handlers/signIn.handler
    events:
      - http:
          path: sign-in
          method: POST
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true
      - http:
          path: sign-in
          method: options
          cors:
            origin: ${self:custom.origins}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: true

plugins:
  - serverless-offline

package:
  exclude:
    - .env

useDotenv: true